//! Wire messages for the pubky-swap marketplace, exchanged as encrypted Pubky DMs.
//!
//! Flow (happy path):
//! ```text
//! Provider --Offer-->            (published to followers / on request)
//! Client   --QuoteRequest-->     Provider
//! Client   <--Quote--            Provider
//! Client   --SwapRequest-->      Provider
//! Client   <--SwapAccept--       Provider   (HTLC address / hold invoice)
//! ... funding, lockup, claim ...
//! both     <--SwapStatusUpdate--> both
//! ```

use crate::swap::{NetworkSpec, SwapDirection, SwapState};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Top-level wire envelope exchanged over the Pubky transport.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum SwapMessage {
    /// Provider → anyone: advertises swap capabilities + rates.
    Offer(SwapOffer),
    /// Client → provider: request a concrete quote against an offer.
    QuoteRequest(QuoteRequest),
    /// Provider → client: a firm, time-limited quote.
    Quote(Quote),
    /// Client → provider: commit to a swap based on a quote.
    SwapRequest(SwapRequest),
    /// Provider → client: details the client needs to proceed (HTLC address, invoice…).
    SwapAccept(SwapAccept),
    /// Either party → counterparty: lifecycle transition.
    SwapStatusUpdate(SwapStatusUpdate),
    /// Either party → counterparty: cooperative signature material.
    /// Reserved for phase-2 Taproot cooperative (key-path) spends.
    CoopSignature(CoopSignature),
    /// Either party → counterparty: abort/reject with a reason.
    Reject(Reject),
}

/// A provider's advertised swap capabilities and rates.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SwapOffer {
    pub offer_id: Uuid,
    pub provider_pkarr: String,
    pub network: NetworkSpec,
    pub directions: Vec<SwapDirection>,
    pub min_amount_sat: u64,
    pub max_amount_sat: u64,
    /// Flat fee component.
    pub base_fee_sat: u64,
    /// Proportional fee, in parts-per-million of the swap amount.
    pub fee_ppm: u64,
    /// On-chain confirmations required before a lockup is treated as final.
    pub required_confirmations: u32,
    /// HTLC timelock, in blocks measured from the lockup.
    pub htlc_timeout_blocks: u32,
    /// Provider's Lightning node id (informational / routing hint).
    pub lightning_node_id: Option<String>,
    /// Unix seconds after which the offer is stale.
    pub valid_until_unix: u64,
}

impl SwapOffer {
    /// Fee the provider charges for a swap of `amount_sat`.
    pub fn quote_fee(&self, amount_sat: u64) -> u64 {
        let proportional = (u128::from(amount_sat) * u128::from(self.fee_ppm) / 1_000_000) as u64;
        self.base_fee_sat.saturating_add(proportional)
    }

    pub fn supports(&self, dir: SwapDirection) -> bool {
        self.directions.contains(&dir)
    }

    pub fn accepts_amount(&self, amount_sat: u64) -> bool {
        amount_sat >= self.min_amount_sat && amount_sat <= self.max_amount_sat
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QuoteRequest {
    pub offer_id: Uuid,
    pub client_pkarr: String,
    pub direction: SwapDirection,
    pub amount_sat: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Quote {
    pub quote_id: Uuid,
    pub offer_id: Uuid,
    pub direction: SwapDirection,
    pub amount_sat: u64,
    pub fee_sat: u64,
    /// What the client ultimately pays (amount + fee for submarine; LN invoice amount for
    /// reverse). Kept explicit so the client can sanity-check before committing.
    pub total_sat: u64,
    pub htlc_timeout_blocks: u32,
    pub required_confirmations: u32,
    pub valid_until_unix: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SwapRequest {
    pub quote_id: Uuid,
    pub client_pkarr: String,
    pub direction: SwapDirection,
    /// SHA256 payment hash (hex). Reverse: generated by the client. Submarine: taken from
    /// the client's Lightning invoice.
    pub payment_hash_hex: String,
    /// Client's claim pubkey (hex, 33-byte compressed). Reverse: claim branch of the
    /// provider's on-chain HTLC.
    pub client_claim_pubkey_hex: Option<String>,
    /// Client's refund pubkey (hex). Submarine: refund branch of the client's own HTLC.
    pub client_refund_pubkey_hex: Option<String>,
    /// Submarine only: the Lightning invoice the provider must pay.
    pub invoice: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SwapAccept {
    pub quote_id: Uuid,
    pub swap_id: Uuid,
    pub direction: SwapDirection,
    /// HTLC redeem script (hex), so both parties can independently verify it.
    pub htlc_script_hex: String,
    /// P2WSH address the funding party must pay into.
    pub htlc_address: String,
    /// Exact amount to lock on-chain.
    pub onchain_amount_sat: u64,
    /// Absolute block height at which the HTLC refund branch becomes spendable.
    pub timeout_block_height: u32,
    /// Provider's pubkey in the HTLC (hex).
    pub provider_pubkey_hex: String,
    /// Reverse only: the Lightning hold invoice the client must pay.
    pub invoice: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SwapStatusUpdate {
    pub swap_id: Uuid,
    pub state: SwapState,
    /// Optional txid / preimage / invoice reference for this transition.
    pub reference: Option<String>,
}

/// Cooperative signature material (phase-2 Taproot key-path spends). The encoding is
/// intentionally opaque until that work lands.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CoopSignature {
    pub swap_id: Uuid,
    pub data_hex: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Reject {
    pub swap_id: Option<Uuid>,
    pub quote_id: Option<Uuid>,
    pub reason: String,
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_offer() -> SwapOffer {
        SwapOffer {
            offer_id: Uuid::nil(),
            provider_pkarr: "provider".to_string(),
            network: NetworkSpec::Regtest,
            directions: vec![SwapDirection::Submarine, SwapDirection::Reverse],
            min_amount_sat: 10_000,
            max_amount_sat: 1_000_000,
            base_fee_sat: 500,
            fee_ppm: 2_000, // 0.2%
            required_confirmations: 1,
            htlc_timeout_blocks: 144,
            lightning_node_id: None,
            valid_until_unix: 0,
        }
    }

    #[test]
    fn quote_fee_is_base_plus_proportional() {
        let offer = sample_offer();
        // 500 base + 0.2% of 1_000_000 = 500 + 2000 = 2500
        assert_eq!(offer.quote_fee(1_000_000), 2_500);
        assert!(offer.supports(SwapDirection::Reverse));
        assert!(offer.accepts_amount(10_000));
        assert!(!offer.accepts_amount(9_999));
    }

    #[test]
    fn swap_message_roundtrips() {
        let msg = SwapMessage::Offer(sample_offer());
        let json = serde_json::to_string(&msg).unwrap();
        let back: SwapMessage = serde_json::from_str(&json).unwrap();
        match back {
            SwapMessage::Offer(o) => assert_eq!(o.base_fee_sat, 500),
            _ => panic!("wrong variant"),
        }
    }
}
